openapi: 3.0.0
info:
  title: PFSS Swagger LNB API - OpenAPI 3.0
  description: |-
    This is a LNB server based on the OpenAPI 3.0 specification.
  termsOfService: http://localhost:8080/terms/
  contact:
    email: pfss@cn.panasonic.com
  license:
    name: Apache 2.0
    url:  http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: 'http://localhost:8080'
    description: Local server
tags:
  - name: User
    description: Everything about user
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: Products
    description: Everything about products
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
paths:
  /users:
    get:
      tags:
        - Users
      summary: Get all lnb users
      description: Get all lnb users infomation
      operationId: getAllUsersInfo
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
              type: array
              items:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: Integer
          format: int64
          description: User ID
        name:
          type: String
          description: User Name
        email:
          type: String
          format: email
          description: User Email