openapi: 3.0.0
info:
  title: PFSS Swagger LNB API - OpenAPI 3.0
  description: |-
    This is a LNB server based on the OpenAPI 3.0 specification.
  termsOfService: http://localhost:8080/terms/
  contact:
    email: pfss@cn.panasonic.com
  license:
    name: Apache 2.0
    url:  http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: 'http://10.194.98.98:8080'
    description: Local server
tags:
  - name: User
    description: Everything about user
    externalDocs:
      description: Find out more about swagger
      url: http://swagger.io
  - name: Products
    description: Everything about products
    externalDocs:
      description: Find out more about swagger
      url: http://swagger.io
paths:
  /users:
    get:
      tags:
        - User
      summary: Get all lnb users
      description: Get all lnb users infomation
      operationId: getAllUsersInfo
      responses:
        '200':
          description: get user success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/create:
    post:
      tags:
        - User
      summary: Create a new lnb user
      description: Create a new lnb user into LNB system
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: The user was successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Bad request (e.g., invalid input)
        '500':
          description: Internal server error
  /users/delete/{id}:
    delete:
      tags:
        - User
      summary: Delete existing lnb user
      description: Delete existing lnb user from system by id 
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          description: ID of user
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid user name
  /users/update:
    put:
      tags:
        - User
      summary: Upate existing lnb user
      description: Upate existing lnb user into LNB system
      operationId: updateUser
      requestBody:
        description: Update user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'          
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid userinfo
        '404':
          description: User not found
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: User ID
          example: 1
        name:
          type: string
          description: User Name
          example: Smith
        email:
          type: string
          description: User Email
          example: Smith@panasonic.com
    UserResponse:
      type: object
      properties:
        status:
          type: string
          description: The status of the user creation request
          example: success
        message:
          type: string
          description: create status message
          example: User created successfully
        user:
          $ref: '#/components/schemas/User'