openapi: 3.0.0
info:
  title: Test Spring Boot API
  version: 1.0.0
  description: test
servers:
  - url: 'http://localhost:8080'
    description: Local server
paths:
  /hellow:
    get:
      summary: return "hellowword"
      operationId: helloword
      responses:
        '200':
          description: success response
          content:
            text/plain:
              schema:
                type: string
                example: Hellow, World!