openapi: 3.0.0
info:
  title: Test Spring Boot API
  version: 1.0.0
  description: test
servers:
  - url: 'http://localhost:8081'
    description: Local server
paths:
  /hello:
    get:
      summary: return "helloword1"
      operationId: hello1
      responses:
        '200':
          description: success response
          content:
            text/plain:
              schema:
                type: string
                example: Hello, World!